---
version: '3.4'

networks:
  proxy:
    external:
      name: proxy

services:

  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entryPoints=web,secure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.pxlnght.com`)" # will be used for certs too
      - "traefik.http.routers.sonarr.middlewares=https-redirect"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certResolver=acme-http"
      - "traefik.http.services.sonarr-svc.loadBalancer.server.port=8989"
    environment:
      - PUID=1001
      - PGID=1005
      - TZ=America/Detroit
    volumes:
      - /fio/opt/sonarr:/config
      - /fio:/fio
      - /fio/opt/qbittorrent-torrents:/downloads
    ports:
      - 8989:8989

  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entryPoints=web,secure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.pxlnght.com`)" # will be used for certs too
      - "traefik.http.routers.radarr.middlewares=https-redirect"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certResolver=acme-http"
      - "traefik.http.services.radarr-svc.loadBalancer.server.port=7878"
    networks:
      - proxy
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=America/Detroit
    volumes:
      - /fio/opt/radarr:/config
      - /fio:/fio
      - /fio/opt/qbittorrent-torrents:/downloads
    ports:
      - 7878:7878

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.entryPoints=web,secure"
      - "traefik.http.routers.jackett.rule=Host(`jackett.pxlnght.com`)" # will be used for certs too
      - "traefik.http.routers.jackett.middlewares=https-redirect"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.tls.certResolver=acme-http"
      - "traefik.http.services.jackett-svc.loadBalancer.server.port=9117"
    environment:
      - PUID=1003
      - PGID=1005
      - TZ=America/Detroit
      - AUTO_UPDATE=true
    volumes:
      - /fio/opt/jackett:/config
      - /fio/opt/jackett/downloads:/downloads
    ports:
      - 9117:9117

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entryPoints=web,secure"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbit.pxlnght.com`)" # will be used for certs too
      - "traefik.http.routers.qbittorrent.middlewares=https-redirect"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.tls.certResolver=acme-http"
      - "traefik.http.services.qbittorrent-svc.loadBalancer.server.port=8080"
    environment:
      - PUID=1002
      - PGID=1005
      - TZ=America/Detroit
      - WEBUI_PORT=8080
    volumes:
      - /fio/opt/qbittorrent:/config
      - /fio/opt/qbittorrent-torrents:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entryPoints=web,secure"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.pxlnght.com`)" # will be used for certs too
      - "traefik.http.routers.overseerr.middlewares=https-redirect"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.tls.certResolver=acme-http"
      - "traefik.http.services.overseerr-svc.loadBalancer.server.port=5055"
    environment:
      - PUID=1008
      - PGID=1005
      - TZ=America/Detroit
    volumes:
      - /fio/opt/overseerr:/config
    ports:
      - 5055:5055
  
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    labels:
      - traefik.enable=false
    environment:
      - TZ=America/Detroit
      - PLEX_UID=1004
      - PLEX_GID=1005
    network_mode: host
    volumes:
      - /fio/opt/plex:/config
      - /fio/opt/plex-transcode:/transcode
      - /fio/library:/data