---
version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    labels:
      - traefik.enable=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        # Checks for updates at midnight
      - WATCHTOWER_SCHEDULE=0 0 0 * * *
        # Restarts containers after updating
      - WATCHTOWER_INCLUDE_RESTARTING=true
        # Removes old images after updating
      - WATCHTOWER_CLEANUP=true
        # Sets timezone to EST
      - TZ=America/Detroit
