---
version: "2.1"

networks:
  proxy:
    external:
      name: proxy

services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smokeping.entryPoints=web,secure"
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.pxlnght.com`)" # will be used for certs too
      - "traefik.http.routers.smokeping.middlewares=https-redirect"
      - "traefik.http.routers.smokeping.tls=true"
      - "traefik.http.routers.smokeping.tls.certResolver=acme-http"
      - "traefik.http.services.smokeping-svc.loadBalancer.server.port=80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /fio/opt/smokeping/config:/config
      - /fio/opt/smokeping/data:/data
    #ports:
    #  - 8082:80
    restart: unless-stopped
