---
version: "3.4"

services:
  factorio:
    image: factoriotools/factorio
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - /fio/game_servers/factorio:/factorio
    restart: always
